/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_mobile_analytics_app_id": "475f7019364a41c2a77a3d9e3fc8f354",
    "aws_mobile_analytics_app_region": "us-west-2",
    "Analytics": {
        "AWSPinpoint": {
            "appId": "475f7019364a41c2a77a3d9e3fc8f354",
            "region": "us-west-2"
        }
    },
    "aws_appsync_graphqlEndpoint": "https://3tiqmikjxrf5xchs3kacvlny5e.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-cjv5y2ud4bhzxocwqs7oor24qu",
    "aws_cognito_identity_pool_id": "us-west-2:7397b7ce-0701-4824-9575-29adfb608e67",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_wrAGgrggS",
    "aws_user_pools_web_client_id": "56dntmapohtlof2ont28bd4pho",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "muvozoprima_bot_dev",
            "alias": "$LATEST",
            "region": "us-west-2"
        }
    ],
    "aws_user_files_s3_bucket": "muvozoprimdeux10d9b83-dev",
    "aws_user_files_s3_bucket_region": "us-west-2",
    "predictions": {
        "interpret": {
            "interpretText": {
                "region": "us-west-2",
                "proxy": false,
                "defaults": {
                    "type": "ALL"
                }
            }
        }
    }
};


export default awsmobile;
